# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "➜"     # The "symbol" segment is being set to "➜"
error_symbol = "✗"

[docker_context]
symbol = " "
disabled = false # enable the module
only_with_files = true # Only show when there's a docker-compose.yml or Dockerfile in the current directory.

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# Nerd font symbols required
# Work well with FiraCode Nerd Font
[aws]
symbol = "  "

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[conda]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
