[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.rumdl]
command = "rumdl"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ty", { name = "ruff", except-features = ["hover"] }]
formatter = { command = "sh", args = [
  "-c",
  "ruff check --fix --force-exclude --select=I001 --exit-zero --no-cache --stdin-filename \"$1\" - | ruff format --force-exclude --stdin-filename \"$1\" -",
  "sh",
  "%{buffer_name}",
] }
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["--stdin-filepath", "%{buffer_name}", "-"] }
auto-format = true

[[language]]
name = "toml"
language-servers = ["tombi"]
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "javascript"
language-servers = ["vtsls"]
auto-format = true

[[language]]
name = "jsx"
language-servers = ["vtsls"]
auto-format = true

[[language]]
name = "typescript"
language-servers = ["vtsls"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["vtsls"]
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "rumdl"]
formatter = { command = "rumdl", args = [
  "check",
  "--fix",
  "--fail-on=never",
  "--stdin",
  "--stdin-filename=%{buffer_name}",
] }
auto-format = true

[[language]]
name = "fish"
auto-format = true

[[language]]
name = "bash"
auto-format = true
