# ~/.config/chezmoi/chezmoi.toml

[data]
  secret_import_ssh_key = "true"
  secret_import_gpg_key = "true"


  git_username = "gazorby"
  git_email = "gazorby@pm.me"
  git_gpg_sign = "true"

  ignore_ping = "true"
  local_hostname_resolution = "true"

  # Control system files management (outside $HOME)
  # values :
  #   - enabled :   enable system management
  #   - disabled :  disable system management
  #   - ask :       prompt the user to copy files or not
  system_config = "disabled"

  filesystem = "btrfs"
