# ~/.config/chezmoi/chezmoi.toml

[data]
bw_chezmoi_item_name = "chezmoi"
# Import ssh private key from bitwarden
# values :
#   - true
#   - false
bw_ssh_import_key = "false"
# ssh private key name
bw_ssh_private_key = "id_rsa"
# ssh public key name
bw_ssh_public_key = "id_rsa.pub"
# Import gpg private key from bitwarden
# values :
#   - true
#   - false
bw_gpg_import_key = "false"
# gpg private key name
bw_gpg_private_key = "gpg.key"

git_username = "gazorby"
git_email = "gazorby@pm.me"
git_gpg_sign = "true"
git_gpg_key_id = "C2B1ACDB1D31A11F229816C0E59988ACE9EF0D6B"

# Ignore ping requests
# values :
#   - true
#   - false
ignore_ping = "true"
# Enabled local hostname resolution ("hostname.local" naming scheme)
# values :
#   - true
#   - false
local_hostname_resolution = "true"

# Control system files management (outside $HOME)
# values :
#   - enabled :   enable system management
#   - disabled :  disable system management
#   - ask :       prompt the user to copy files or not
system_config = "disabled"

# filesystem specific config
# values :
#   - btrfs: (Copy snapper config)
filesystem = "btrfs"
