# ~/.config/chezmoi/chezmoi.toml

[data]
  # Import ssh private key from bitwarden
  # values :
  #   - true
  secret_import_ssh_key = "true"
  # Import gpg private key from bitwarden
  # values :
  #   - true
  secret_import_gpg_key = "true"

  git_username = "gazorby"
  git_email = "gazorby@pm.me"
  git_gpg_sign = "true"
  git_gpg_key_id = "C2B1ACDB1D31A11F229816C0E59988ACE9EF0D6B"

  # Ignore ping requests
  # values :
  #   - true
  ignore_ping = "true"
  # Enabled local hostname resolution ("hostname.local" naming scheme)
  # values :
  #   - true
  local_hostname_resolution = "true"

  # Control system files management (outside $HOME)
  # values :
  #   - enabled :   enable system management
  #   - disabled :  disable system management
  #   - ask :       prompt the user to copy files or not
  system_config = "disabled"

  # filesystem specific config
  # values :
  #   - btrfs: Copy snapper config
  filesystem = "btrfs"
