# Built-in preset or a file in themes/
theme_preset = "monokai-pro"

[[custom_keybindings.diff]]
key = "o"
name = "open file in hx"
command = 'cd "$GLAB_TUI_REPO_PATH" && hx "+$GLAB_TUI_LINE_NUMBER" "$GLAB_TUI_FILE_PATH"'

[[custom_keybindings.mrs]]
key = "w"
name = "diff in delta"
command = 'pr_delta'

[[custom_keybindings.diff]]
key = "w"
name = "diff in delta"
command = 'pr_delta'

[[custom_keybindings.mrs]]
key = "W"
name = "side-by-side diff in delta"
command = 'pr_delta -s'

[[custom_keybindings.diff]]
key = "W"
name = "side-by-side diff in delta"
command = 'pr_delta -s'
