bg = "#282828"
border = "#928374"
border_focused = "#b8bb26"
header_fg = "#b8bb26"
highlight_bg = "#3c3836"
inactive_bg = "#32302f"
text_normal = "#ebdbb2"
text_muted = "#928374"
checked_bg = "#3f5560"
green = "#b8bb26"
green_bg = "#323714"
red = "#cc241d"
red_bg = "#3c140f"
blue = "#83a598"
blue_bg = "#192828"
yellow = "#d69315"
yellow_bg = "#32280f"
purple = "#d3869b"
purple_bg = "#371e28"

# ── Label palette ──
label_palette_0 = "#d3869b"
label_palette_1 = "#83a598"
label_palette_2 = "#b8bb26"
label_palette_3 = "#d69315"
label_palette_4 = "#cc241d"
label_palette_5 = "#f08cb4"
label_palette_6 = "#fa7850"
label_palette_7 = "#28c8c8"
label_palette_8 = "#b4e628"
label_palette_9 = "#dca0ff"
diff_gutter_bg = "#282828"
diff_sep = "#928374"

badge_group_bg = "#00bcd4"
